rootProject.name = 'real-estate-backend-architecture-lab'

include 'AuthService'
include 'UserProfileService'
include 'AgentService'
include 'BuyerService'
include 'SellerService'
include 'PropertyService'
include 'ConfigServerLocal'
include 'ConfigServerRemote'
include 'ApiGatewayService'
include 'EurekaServer'
include 'SearchService'
