dependencies {
    implementation libs.springBootWeb
    implementation libs.springBootValidation
    implementation libs.swaggerApi
    implementation libs.mapStruct
    implementation libs.springCloudEurekaClient
    implementation libs.springBootDataMongoDb
    implementation libs.springCloudStarterConfig
    implementation libs.springBootActuator
    implementation libs.springBootZipkin

    testImplementation libs.springBootTest
    testImplementation libs.springBootWebMvcTest
    testImplementation libs.testcontainersJunitJupiter
    testImplementation libs.testcontainersMongoDb
    testImplementation libs.archUnitJunit5
}
