dependencies {
    implementation libs.springBootWeb
    implementation libs.springBootValidation
    implementation libs.swaggerApi
    implementation libs.mapStruct
    implementation libs.springCloudEurekaClient
    implementation libs.springBootDataCassandra
    implementation libs.springCloudStarterConfig
    implementation libs.springBootActuator
    implementation libs.springBootZipkin

    testImplementation libs.testcontainersJunitJupiter
    testImplementation "org.testcontainers:testcontainers-cassandra:$versions.testcontainers"
    testImplementation libs.archUnitJunit5
}
