server:
  port: 9093

spring:
  couchbase:
    connection-string: ${BUYER_COUCHBASE_CONNECTION_STRING:couchbase://localhost}
    username: ${BUYER_DB_USERNAME}
    password: ${BUYER_DB_PASSWORD}
    env:
      timeouts:
        key-value: ${BUYER_COUCHBASE_KV_TIMEOUT:2500ms}
        query: ${BUYER_COUCHBASE_QUERY_TIMEOUT:75s}
  data:
    couchbase:
      bucket-name: ${BUYER_COUCHBASE_BUCKET:buyer}
      scope-name: ${BUYER_COUCHBASE_SCOPE:buyer_service}

buyer:
  couchbase:
    collection-name: ${BUYER_COUCHBASE_COLLECTION:preferences}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
