server:
  port: 9094

spring:
  mongodb:
    host: ${PROPERTY_MONGO_HOST:localhost}
    port: ${PROPERTY_MONGO_PORT:27018}
    database: ${PROPERTY_MONGO_DB_NAME:micro_property_service_db}
    username: ${PROPERTY_MONGO_USERNAME:${PROPERTY_MONGO_ROOT_USERNAME}}
    password: ${PROPERTY_MONGO_PASSWORD:${PROPERTY_MONGO_ROOT_PASSWORD}}
    authentication-database: ${PROPERTY_MONGO_AUTH_DB:admin}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
