server:
  port: 9095

spring:
  cassandra:
    contact-points: ${SELLER_CASSANDRA_CONTACT_POINTS:localhost}
    port: ${SELLER_CASSANDRA_PORT:9042}
    keyspace-name: ${SELLER_CASSANDRA_KEYSPACE:seller_service}
    local-datacenter: ${SELLER_CASSANDRA_LOCAL_DATACENTER:datacenter1}
    schema-action: none
    request:
      timeout: ${SELLER_CASSANDRA_REQUEST_TIMEOUT:5s}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
