dependencies {
    implementation libs.springBootWeb
    implementation libs.springBootValidation
    implementation libs.swaggerApi
    implementation libs.mapStruct
    implementation libs.springCloudEurekaClient
    implementation libs.springBootDataCouchbase
    implementation libs.springCloudStarterConfig
    implementation libs.springBootActuator
    implementation libs.springBootZipkin

    testImplementation libs.springBootTest
    testImplementation libs.springBootWebMvcTest
    testImplementation libs.testcontainersJunitJupiter
    testImplementation libs.testcontainersCouchbase
    testImplementation libs.archUnitJunit5
}


tasks.named('test') {
    systemProperty 'spring.config.import', 'optional:classpath:/buyer-test.properties'
    systemProperty 'spring.cloud.config.enabled', 'false'
    systemProperty 'eureka.client.enabled', 'false'
}
